set(COMMON_SOURCES
    ${CODE_DIR}/Common/FileDialogs.cpp
    ${CODE_DIR}/Common/FileDialogs.hpp
    ${CODE_DIR}/Common/Filesystem.cpp
    ${CODE_DIR}/Common/Filesystem.hpp
    ${CODE_DIR}/Common/Platform.hpp
    ${CODE_DIR}/Common/Result.hpp
    ${CODE_DIR}/Common/Str.hpp
    ${CODE_DIR}/Common/Timer.hpp
    ${CODE_DIR}/Common/Types.hpp
    ${CODE_DIR}/Common/WindowsHelpers.cpp
    ${CODE_DIR}/Common/WindowsHelpers.hpp
)