set(ENGINE_SOURCES
    ${CODE_DIR}/Engine/ArenaAllocator.cpp
    ${CODE_DIR}/Engine/ArenaAllocator.hpp
    ${CODE_DIR}/Engine/BehaviorComponent.cpp
    ${CODE_DIR}/Engine/BehaviorComponent.hpp
    ${CODE_DIR}/Engine/BloomEffect.cpp
    ${CODE_DIR}/Engine/BloomEffect.hpp
    ${CODE_DIR}/Engine/Camera.cpp
    ${CODE_DIR}/Engine/Camera.hpp
    ${CODE_DIR}/Engine/Clock.cpp
    ${CODE_DIR}/Engine/Clock.hpp
    ${CODE_DIR}/Engine/ColorGradeEffect.cpp
    ${CODE_DIR}/Engine/ColorGradeEffect.hpp
    ${CODE_DIR}/Engine/ComponentManager.hpp
    ${CODE_DIR}/Engine/ComputeEffect.hpp
    ${CODE_DIR}/Engine/D3D.hpp
    ${CODE_DIR}/Engine/DebugUI.hpp
    ${CODE_DIR}/Engine/DevConsole.cpp
    ${CODE_DIR}/Engine/DevConsole.hpp
    ${CODE_DIR}/Engine/EngineCommon.hpp
    ${CODE_DIR}/Engine/EntityId.hpp
    ${CODE_DIR}/Engine/Game.cpp
    ${CODE_DIR}/Engine/Game.hpp
    ${CODE_DIR}/Engine/GeometryBuffer.hpp
    ${CODE_DIR}/Engine/Input.hpp
    ${CODE_DIR}/Engine/InputCodes.hpp
    ${CODE_DIR}/Engine/InputLayouts.hpp
    ${CODE_DIR}/Engine/Lights.hpp
    ${CODE_DIR}/Engine/Material.cpp
    ${CODE_DIR}/Engine/Material.hpp
    ${CODE_DIR}/Engine/MaterialParser.cpp
    ${CODE_DIR}/Engine/MaterialParser.hpp
    ${CODE_DIR}/Engine/Math.hpp
    ${CODE_DIR}/Engine/Memory.hpp
    ${CODE_DIR}/Engine/Model.cpp
    ${CODE_DIR}/Engine/Model.hpp
    ${CODE_DIR}/Engine/ModelComponent.cpp
    ${CODE_DIR}/Engine/ModelComponent.hpp
    ${CODE_DIR}/Engine/ModelLoader.cpp
    ${CODE_DIR}/Engine/ModelLoader.hpp
    ${CODE_DIR}/Engine/Mouse.cpp
    ${CODE_DIR}/Engine/Mouse.hpp
    ${CODE_DIR}/Engine/Platform.hpp
    ${CODE_DIR}/Engine/PoolAllocator.cpp
    ${CODE_DIR}/Engine/PoolAllocator.hpp
    ${CODE_DIR}/Engine/PostProcessSystem.cpp
    ${CODE_DIR}/Engine/PostProcessSystem.hpp
    ${CODE_DIR}/Engine/RasterizerState.cpp
    ${CODE_DIR}/Engine/RasterizerState.hpp
    ${CODE_DIR}/Engine/RenderContext.cpp
    ${CODE_DIR}/Engine/RenderContext.hpp
    ${CODE_DIR}/Engine/RenderSystem.cpp
    ${CODE_DIR}/Engine/RenderSystem.hpp
    ${CODE_DIR}/Engine/Resource.hpp
    ${CODE_DIR}/Engine/ResourceManager.cpp
    ${CODE_DIR}/Engine/ResourceManager.hpp
    ${CODE_DIR}/Engine/Scene.cpp
    ${CODE_DIR}/Engine/Scene.hpp
    ${CODE_DIR}/Engine/SceneParser.cpp
    ${CODE_DIR}/Engine/SceneParser.hpp
    ${CODE_DIR}/Engine/SceneState.hpp
    ${CODE_DIR}/Engine/ScriptEngine.hpp
    ${CODE_DIR}/Engine/ScriptTypeRegistry.hpp
    ${CODE_DIR}/Engine/Shader.cpp
    ${CODE_DIR}/Engine/Shader.hpp
    ${CODE_DIR}/Engine/StaticResources.cpp
    ${CODE_DIR}/Engine/StaticResources.hpp
    ${CODE_DIR}/Engine/Texture.cpp
    ${CODE_DIR}/Engine/Texture.hpp
    ${CODE_DIR}/Engine/TextureLoader.cpp
    ${CODE_DIR}/Engine/TextureLoader.hpp
    ${CODE_DIR}/Engine/TonemapEffect.cpp
    ${CODE_DIR}/Engine/TonemapEffect.hpp
    ${CODE_DIR}/Engine/TransformComponent.cpp
    ${CODE_DIR}/Engine/TransformComponent.hpp
    ${CODE_DIR}/Engine/TransformMatrices.hpp
    ${CODE_DIR}/Engine/Volatile.hpp
)

set(SHADER_INCLUDE
    ${CMAKE_CURRENT_SOURCE_DIR}/Engine/Shaders/Header
)